src/Entity/Beneficiaire.php
<?php

namespace App\Entity;

use App\Repository\BeneficiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: BeneficiaireRepository::class)]
#[UniqueEntity(fields: ['email_benef'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['email_benef'], message: 'There is already an account with this email')]
class Beneficiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_benef = null;

    #[ORM\Column(length: 13)]
    #[Assert\NotBlank(message:"Rib is required.")]
    private ?string $rib_benef = null;

    #[ORM\Column(length: 13)]
    #[Assert\NotBlank(message:"Family name is required.")]
    private ?string $nom_benef = null;

    #[ORM\Column(length: 13)]
    #[Assert\NotBlank(message:"Name is required.")]
    private ?string $prenom_benef = null;

    
    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message:"Email is required.")]
    #[Assert\Email(message:" The Email '{{ value }}' is not a valid email. ")]
    private ?string $email_benef = null;
    

    // Jointure

    #[ORM\OneToMany(mappedBy: 'beneficiaire', targetEntity: Virement::class)]
    #[ORM\JoinColumn( referencedColumnName:"id_virement")]
    private Collection $virements;




    public function __construct()
    {
        $this->virements = new ArrayCollection();
    }

     
   

    public function getIdBenef(): ?int
    {
        return $this->id_benef;
    }

    public function getRibBenef(): ?string
    {
        return $this->rib_benef;
    }

    public function setRibBenef(string $rib_benef): self
    {
        $this->rib_benef = $rib_benef;

        return $this;
    }

    public function getNomBenef(): ?string
    {
        return $this->nom_benef;
    }

    public function setNomBenef(string $nom_benef): self
    {
        $this->nom_benef = $nom_benef;

        return $this;
    }

    public function getPrenomBenef(): ?string
    {
        return $this->prenom_benef;
    }

    public function setPrenomBenef(string $prenom_benef): self
    {
        $this->prenom_benef = $prenom_benef;

        return $this;
    }

    public function getEmailBenef(): ?string
    {
        return $this->email_benef;
    }

    public function setEmailBenef(string $email_benef): self
    {
        $this->email_benef = $email_benef;

        return $this;
    }

    /**
     * @return Collection<int, Virement>
     */
    public function getVirements(): Collection
    {
        return $this->virements;
    }

    public function addVirement(Virement $virement): self
    {
        if (!$this->virements->contains($virement)) {
            $this->virements->add($virement);
            $virement->setBeneficiaire($this);
        }

        return $this;
    }

    public function removeVirement(Virement $virement): self
    {
        if ($this->virements->removeElement($virement)) {
            // set the owning side to null (unless already changed)
            if ($virement->getBeneficiaire() === $this) {
                $virement->setBeneficiaire(null);
            }
        }

        return $this;
    }
}

src/Form/BeneficiaireType.php
<?php

namespace App\Form;

use App\Entity\Beneficiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BeneficiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rib_benef')
            ->add('nom_benef')
            ->add('prenom_benef')
            ->add('email_benef')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Beneficiaire::class,
        ]);
    }
}

src/Controller/BeneficiaireController.php
<?php

namespace App\Controller;

use App\Entity\Beneficiaire;
use App\Form\BeneficiaireType;
use App\Repository\BeneficiaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Services\QrcodeService;
use App\Form\SearchType;



#[Route('/beneficiaire')]
class BeneficiaireController extends AbstractController
{
    #[Route('/list', name: 'app_beneficiaire_index', methods: ['GET'])]
    public function index(BeneficiaireRepository $beneficiaireRepository): Response
    {
        return $this->render('beneficiaire/index.html.twig', [
            'beneficiaires' => $beneficiaireRepository->findAll(),
        ]);
    }

    #[Route ('/search' , name : 'search', methods: ['POST'])]
    function search (BeneficiaireRepository $beneficiaireRepository, Request $request) {
        $data = $request -> get('search');
        $beneficiaire = $beneficiaireRepository ->findBy( ['rib_benef'=> $data]);
        return $this -> render('beneficiaire/index.html.twig' ,[
                'beneficiaires' => $beneficiaire
            ]
        );
    }

    #[Route('/new', name: 'app_beneficiaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BeneficiaireRepository $beneficiaireRepository): Response
    {
        $beneficiaire = new Beneficiaire();
        $form = $this->createForm(BeneficiaireType::class, $beneficiaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $beneficiaireRepository->save($beneficiaire, true);
            return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('beneficiaire/new.html.twig', [
            'beneficiaire' => $beneficiaire,
            'form' => $form,
        ]);
    }

    #[Route("/{id_benef}/qrcode", name: 'app_qrcode',methods: ['GET'])]
    public function qrcodeGenerator(Beneficiaire $beneficiaire,QrcodeService $qrcodeService): Response
    {
       $qrCode = null;
       //$sahraoui=$beneficiaireRpeository->find($id_benef);
       
       $data="\n Rib : ";
       $data.=$beneficiaire->getRibBenef();
       $data.="\n Email : " .$beneficiaire->getEmailBenef();
       $data.="\n Nom : ".$beneficiaire->getNomBenef();
       $data.= "\n Prenom : ".$beneficiaire->getPrenomBenef();

           $qrCode = $qrcodeService->qrcode($data);
            

       return $this->render('beneficiaire/show.html.twig', [
        'beneficiaire' => $beneficiaire,
           'qrCode' => $qrCode
       ]);
    }

    #[Route('/{id_benef}', name: 'app_beneficiaire_show', methods: ['GET'])]
    public function show(Beneficiaire $beneficiaire): Response
    {
        $qrCode=false;

        return $this->render('beneficiaire/show.html.twig', [
            'beneficiaire' => $beneficiaire,
            'qrCode' => $qrCode
        ]);
    }

    #[Route('/{id_benef}/edit', name: 'app_beneficiaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Beneficiaire $beneficiaire, BeneficiaireRepository $beneficiaireRepository): Response
    {
        $form = $this->createForm(BeneficiaireType::class, $beneficiaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $beneficiaireRepository->save($beneficiaire, true);

            return $this->redirectToRoute('app_beneficiaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('beneficiaire/edit.html.twig', [
            'beneficiaire' => $beneficiaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id_benef}', name: 'app_beneficiaire_delete', methods: ['POST'])]
    public function delete(Request $request, Beneficiaire $beneficiaire, BeneficiaireRepository $beneficiaireRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$beneficiaire->getIdBenef(), $request->request->get('_token'))) {
            $beneficiaireRepository->remove($beneficiaire, true);
        }

        return $this->redirectToRoute('app_beneficiaire_index', [], Response::HTTP_SEE_OTHER);
    }
    
   
    
    

}

templates/beneficiaire/_delete_form.html.twig
<form method="post" action="{{ path('app_beneficiaire_delete', {'id_benef': beneficiaire.idBenef}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ beneficiaire.idBenef) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/beneficiaire/_form.html.twig
{% extends './base_front.html.twig' %}
{% block body %}

	<section class="account-wrap ptb-100">

		<div class="container">
			<div class="account-form">
        
				{{ form_start(form) }}

				<div>
					<div class="section-title style1 text-center mb-40">
						<span>Beneficier</span>
						<h2>Informations Personnelles
						</h2>
					</div>
					<div class="row">
						<div class="col-md-612">
							<div class="form-group">


								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="rib_benef">Rib du beneficiaire</label>
											{{ form_widget(form.rib_benef,{'attr':{'class':'form-control','placeholder':"rib_benef"}})}}
											{{ form_errors(form.rib_benef) }}
										</div>
									</div>
                                    <div class="col-md-6">
										<div class="form-group">
											<label for="nom_benef">Nom de beneficiaire</label>
											{{ form_widget(form.nom_benef,{'attr':{'class':'form-control','placeholder':"nom_benef"}})}}
											{{ form_errors(form.nom_benef) }}
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label for="prenom_benef">Prenom de beneficiaire</label>
											{{ form_widget(form.prenom_benef,{'attr':{'class':'form-control','placeholder':"prenom_benef"}})}}
											{{ form_errors(form.prenom_benef) }}
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label for="email_benef">Email de beneficiaire</label>
											{{ form_widget(form.email_benef,{'attr':{'class':'form-control','placeholder':"email_benef"}})}}
											{{ form_errors(form.email_benef) }}
										</div>
									</div>
						</div>


						<br/>

					</div>
				</div>

				
                  <button type="submit" class="btn btn-primary">Save</button>
                  
				{{ form_end(form) }}
			</div>
		</div>


	</section>


{% endblock %}

templates/beneficiaire/edit.html.twig
{% extends './base_front.html.twig' %}

{% block title %}Edit Beneficiaire{% endblock %}

{% block body %}
    <h1>Edit Beneficiaire</h1>

    {{ include('beneficiaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_beneficiaire_index') }}">back to list</a>

    {{ include('beneficiaire/_delete_form.html.twig') }}
{% endblock %}

templates/beneficiaire/index.html.twig
{% extends './base_front.html.twig' %}

{% block title %}Liste des beneficiaires{% endblock %}

{% block body %}

</br>
</br>
</br>
</br>
</br>
</br>
    <h1> </h1>
    <ul class="navbar-nav w-100">
               
                    <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search" method="post" action="{{ path('search') }}">
                        <input type="text" name = "search"  class="form-control" placeholder="Search rib">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><input class="btn btn-success" type="submit"  value="search"></li>
                        </ol>
                    </form>
                </li>
            </ul>

    <table class="table">
        <thead>
            <tr>
                
                <th>Rib_benef</th>
                <th>Nom_benef</th>
                <th>Prenom_benef</th>
                <th>Email_benef</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for beneficiaire in beneficiaires %}
            <tr>
                
                <td>{{ beneficiaire.ribBenef }}</td>
                <td>{{ beneficiaire.nomBenef }}</td>
                <td>{{ beneficiaire.prenomBenef }}</td>
                <td>{{ beneficiaire.emailBenef }}</td>
                <td>
                   <form method="post" action="{{ path('app_beneficiaire_delete', {'id_benef': beneficiaire.idBenef}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ beneficiaire.idBenef) }}">
    <button class="btn btn-danger">Delete</button>
</form>

                    <a href="{{ path('app_beneficiaire_edit', {'id_benef': beneficiaire.idBenef}) }}">edit</a>   
                    <a href="{{ path('app_beneficiaire_show', {'id_benef': beneficiaire.idBenef}) }}">show</a>

                                 
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn style1" href="{{ path('app_beneficiaire_new') }}">Create new</a>
    <br>
    <br>
        {% endblock %}

templates/beneficiaire/mypdf.html.twig
<div class="col-lg-12 grid-margin stretch-card-dark">
                    <div class="card-dark">
                        <div class="card-body-dark">
                            <div class="table-responsive-dark">
                                <table class="table table-striped-dark ">
                                    <thead>
                                    <tr>
                                       
                                        <th>Rib_benef</th>
                <th>Nom_benef</th>
                <th>Prenom_benef</th>
                <th>Email_benef</th>
                <th>actions</th>
                                      
                                    </tr>
                                    </thead>
                                    <tbody>
                                 {% for beneficiaire in beneficiaire %}
                                    <tr onclick="">
                                      
                                           
                                       <td>{{ beneficiaire.ribBenef }}</td>
                <td>{{ beneficiaire.nomBenef }}</td>
                <td>{{ beneficiaire.prenomBenef }}</td>
                <td>{{ beneficiaire.emailBenef }}</td>
                <td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </div>

templates/beneficiaire/new.html.twig
{% extends './base_front.html.twig' %}

{% block title %}New Beneficiaire{% endblock %}

{% block body %}
    <h1>Create new Beneficiaire</h1>

    {{ include('beneficiaire/_form.html.twig') }}

    <a href="{{ path('app_beneficiaire_index') }}">back to list</a>
{% endblock %}

templates/beneficiaire/qrcode.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="example-wrapper">
</br>
</br>
</br>
</br>
</br>
</br>
    <h1>Votre QR Code : ✅</h1> <hr>

    <div class="row">
        <div class="col-md-6">
            {{ form_start(form) }}
                {{ form_row(form.name, {'attr': {'class': 'form-control', 'placeholder': 'Recherche'}}) }}
                <hr>
                <button type="submit" class="btn btn-success btn-block">Recherche</button>
            {{ form_end(form) }}
        </div>
        <div class="col-md-6">
            {% if qrCode %}
                <img src="{{ qrCode }}" alt="qr-code">
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/beneficiaire/show.html.twig
{% extends './base_front.html.twig' %}

{% block title %}Beneficiaire{% endblock %}

{% block body %}
</br>
</br>
</br>
</br>
</br>
</br>
    <h1>Beneficiaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id Beneficiaire</th>
                <td>{{ beneficiaire.idBenef }}</td>
            </tr>
            <tr>
                <th>Rib Beneficiaire</th>
                <td>{{ beneficiaire.ribBenef }}</td>
            </tr>
            <tr>
                <th>Nom Beneficiaire</th>
                <td>{{ beneficiaire.nomBenef }}</td>
            </tr>
            <tr>
                <th>Prenom Beneficiaire</th>
                <td>{{ beneficiaire.prenomBenef }}</td>
            </tr>
            <tr>
                <th>Email Beneficiaire</th>
                <td>{{ beneficiaire.emailBenef }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_beneficiaire_index') }}">Back to list</a>
    <a class="btn btn-danger" href="{{ path('app_qrcode', {'id_benef': beneficiaire.idBenef}) }}">QR Code</a>


    <div class="one-third mb-4 mb-md-0">
                                        <div>
                                        {% if qrCode %}
                                            <img src="{{ qrCode }}" alt="qr-code">
                                        {% endif %}
                                        </div>
                                 </div>
{% endblock %}