src/Entity/Depenses.php
<?php

namespace App\Entity;

use App\Repository\DepensesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\GreaterThan;
#[ORM\Entity(repositoryClass: DepensesRepository::class)]
class Depenses
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_depense = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"le titre doit etre remplir ")]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Rib doit etre remplir ")]
    private ?string $prenom_destinataire = null;

    #[ORM\Column(length: 255)]
     /**
     * @Assert\Regex(pattern="/^[0-9]+$/",message="Le rib doit contenir uniquement des entiers" )
     */
    private ?string $rib_destinataire = null;

    #[ORM\Column]
  
    private ?int $montant = null;

    #[ORM\Column(length: 7)]
    private ?string $backgroundcolor = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    /**
     * @Assert\GreaterThan("today", message="La date doit être supérieure à aujourd'hui")
     */
    private ?\DateTimeInterface $datedebut = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie_depense = null;

    #[ORM\Column(length: 255)]
    private ?string $type_depense = null;

    #[ORM\ManyToOne(inversedBy: 'depenses')]
    #[ORM\JoinColumn(onDelete:"CASCADE")] 
     

    private ?Budget $idbudget = null;

    public function getIddepense(): ?int
    {
        return $this->id_depense;
    }
    public function setIddepense(string $title): self
    {
        $this->id_depense = $id_depense;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrenomDestinataire(): ?string
    {
        return $this->prenom_destinataire;
    }

    public function setPrenomDestinataire(string $prenom_destinataire): self
    {
        $this->prenom_destinataire = $prenom_destinataire;

        return $this;
    }

    public function getRibDestinataire(): ?string
    {
        return $this->rib_destinataire;
    }

    public function setRibDestinataire(string $rib_destinataire): self
    {
        $this->rib_destinataire = $rib_destinataire;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getBackgroundcolor(): ?string
    {
        return $this->backgroundcolor;
    }

    public function setBackgroundcolor(string $backgroundcolor): self
    {
        $this->backgroundcolor = $backgroundcolor;

        return $this;
    }

    public function getDatedebut(): ?\DateTimeInterface
    {
        return $this->datedebut;
    }

    public function setDatedebut(\DateTimeInterface $datedebut): self
    {
        $this->datedebut = $datedebut;

        return $this;
    }

    public function getCategorieDepense(): ?string
    {
        return $this->categorie_depense;
    }

    public function setCategorieDepense(string $categorie_depense): self
    {
        $this->categorie_depense = $categorie_depense;

        return $this;
    }

    public function getTypeDepense(): ?string
    {
        return $this->type_depense;
    }

    public function setTypeDepense(string $type_depense): self
    {
        $this->type_depense = $type_depense;

        return $this;
    }

    public function getIdbudget(): ?Budget
    {
        return $this->idbudget;
    }

    public function setIdbudget(?Budget $idbudget): self
    {
        $this->idbudget = $idbudget;

        return $this;
    }
}

src/Controller/BackDepensesController.php
<?php

namespace App\Controller;

use App\Entity\Depenses;
use App\Form\DepensesType;
use App\Repository\DepensesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/back/depenses')]
class BackDepensesController extends AbstractController
{
    #[Route('/', name: 'app_back_depenses_index', methods: ['GET'])]
    public function index(DepensesRepository $depensesRepository): Response
    {
        return $this->render('back_depenses/index.html.twig', [
            'depenses' => $depensesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_back_depenses_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DepensesRepository $depensesRepository): Response
    {
        $depense = new Depenses();
        $form = $this->createForm(DepensesType::class, $depense);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $depensesRepository->save($depense, true);

            return $this->redirectToRoute('app_back_depenses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back_depenses/new.html.twig', [
            'depense' => $depense,
            'form' => $form,
        ]);
    }

    #[Route('/{id_depense}', name: 'app_back_depenses_show', methods: ['GET'])]
    public function show(Depenses $depense): Response
    {
        return $this->render('back_depenses/show.html.twig', [
            'depense' => $depense,
        ]);
    }

    #[Route('/{id_depense}/edit', name: 'app_back_depenses_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Depenses $depense, DepensesRepository $depensesRepository): Response
    {
        $form = $this->createForm(DepensesType::class, $depense);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $depensesRepository->save($depense, true);

            return $this->redirectToRoute('app_back_depenses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back_depenses/edit.html.twig', [
            'depense' => $depense,
            'form' => $form,
        ]);
    }

    #[Route('/{id_depense}', name: 'app_back_depenses_delete', methods: ['POST'])]
    public function delete(Request $request, Depenses $depense, DepensesRepository $depensesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$depense->getId_depense(), $request->request->get('_token'))) {
            $depensesRepository->remove($depense, true);
        }

        return $this->redirectToRoute('app_back_depenses_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back_depenses/_delete_form.html.twig
<form method="post" action="{{ path('app_depenses_delete', {'id_depense': depense.idDepense}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ depense.idDepense) }}">
    <button ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
      </svg></button>
</form>

templates/back_depenses/_form.html.twig
    

<div class="content-wrapper">

 

  
    <section class="account-wrap ptb-100">
    <div class="container">
    <div class="section-title style1 text-center mb-40">
    <a href="{{ path('app_back_depenses_index') }}">back to list</a>
    <h2>Formulaire De Depense</h2>
    </div>
    <div class="account-form">
    {{ form_start(form)}}
    <div class="row">
    <div class="col-md-6">
    <div class="form-group">
    
    <label for="fname">Titre</label>
    
    {{ form_widget(form.title) }}
    {{ form_errors(form.title) }}
    
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="phone">Prenom Destinataire</label>
    {{ form_widget(form.prenom_destinataire) }}
    {{ form_errors(form.prenom_destinataire) }}
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="email">Rib Destinataire</label>
    {{ form_widget(form.rib_destinataire) }}
    {{ form_errors(form.rib_destinataire) }}
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="email">Montant</label>
    {{ form_widget(form.montant) }}
    {{ form_errors(form.montant) }}
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="dob">Date Debut</label>
    {{ form_widget(form.datedebut) }}
    {{ form_errors(form.datedebut) }}
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="gender">type de depense</label>
    {{ form_widget(form.type_depense) }}
    {{ form_errors(form.type_depense) }}
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="pname">Backgroundcolor</label>
    {{ form_widget(form.backgroundcolor) }}
    {{ form_errors(form.backgroundcolor) }}
    </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
        <label for="phone">Categorie Depense</label>
        {{ form_widget(form.categorie_depense) }}
        {{ form_errors(form.categorie_depense) }}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group" type="hidden">
      <input type="hidden"  >
         {{ form_widget(form.idbudget) }}
        </input>
        </div>
    </div>
    <div class="col-md-12">
    <button type="submit" class="btn style1 w-100 d-block"> save</button>
    </div>
    </div>

        
    {{ form_end(form) }}
</div>
    </div>
    </section>
    
    </div>

templates/back_depenses/edit.html.twig
{% extends './base_agent.html.twig' %}

{% block body %}
    <h1>Edit Depenses</h1>

    {{ include('back_depenses/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/back_depenses/index.html.twig
{% extends './base_agent.html.twig' %}

{% block title %}Depenses index{% endblock %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"> </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">Home</a></li>
                        <li class="breadcrumb-item active">Depenses table</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
   
    <a href="{{ path('app_back_depenses_new') }}">Ajouter un Depense</a>
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Prenom_destinataire</th>
                <th>Rib_destinataire</th>
                <th>Montant</th>
                <th>Datedebut</th>
                <th>Categorie_depense</th>
                <th>Type_depense</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
        {% for depense in depenses %}
            <tr>
                <td>{{ depense.title }}</td>
                <td>{{ depense.prenomDestinataire }}</td>
                <td>{{ depense.ribDestinataire }}</td>
                <td>{{ depense.montant }}</td>
                <td>{{ depense.datedebut ? depense.datedebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ depense.categorieDepense }}</td>
                <td>{{ depense.typeDepense }}</td>
                <td> <button>
                    <a href="{{ path('app_back_depenses_edit', {'id_depense': depense.idDepense}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                      </svg></a></button>
                    
                </td>
                <td>
                    {{ include('back_depenses/_delete_form.html.twig') }}
                </td>    
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
   
{% endblock %}

templates/back_depenses/new.html.twig
{% extends './base_agent.html.twig' %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"> </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">Home</a></li>
                        <li class="breadcrumb-item active">Budget table</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    {{ include('back_depenses/_form.html.twig') }}

{% endblock %}

templates/back_depenses/show.html.twig
<!DOCTYPE html>

<title>Depenses</title>

{% block body %}
    <h1>Depenses</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_depense</th>
                <td>{{ depense.idDepense }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ depense.title }}</td>
            </tr>
            <tr>
                <th>Prenom_destinataire</th>
                <td>{{ depense.prenomDestinataire }}</td>
            </tr>
            <tr>
                <th>Rib_destinataire</th>
                <td>{{ depense.ribDestinataire }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ depense.montant }}</td>
            </tr>
            <tr>
                <th>Backgroundcolor</th>
                <td>{{ depense.backgroundcolor }}</td>
            </tr>
            <tr>
                <th>Datedebut</th>
                <td>{{ depense.datedebut ? depense.datedebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Categorie_depense</th>
                <td>{{ depense.categorieDepense }}</td>
            </tr>
            <tr>
                <th>Type_depense</th>
                <td>{{ depense.typeDepense }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_back_depenses_index') }}">back to list</a>

    <a href="{{ path('app_back_depenses_edit', {'id_depense': depense.id_depense}) }}">edit</a>

    {{ include('back_depenses/_delete_form.html.twig') }}
{% endblock %}